#secrets:
#    1password-credentials-json:
#        file: /etc/komodo/1password-credentials.json

x-1password-credentials-secret: &1password-credentials-secret
    - source: 1password-credentials-json
      target: /run/secrets/1password-credentials.json
      mode: 0o444
x-op-session: &op-session
    #OP_SESSION: /home/opuser/.op/1password-credentials.json
    OP_SESSION: ${OP_SESSION}
#x-volumes: !override &volumes
#    - type: bind
#      source: /etc/komodo/1password-credentials.json
#      target: /home/opuser/.op/1password-credentials.json
#      read_only: true
#      bind:
#          create_host_path: false

services:
    komodo-op:
        environment: !override
            KOMODO_API_KEY: "${KOMODO_API_KEY:?}"
            KOMODO_API_SECRET: "${KOMODO_API_SECRET:?}"
            KOMODO_HOST: "${KOMODO_HOST:?}"
            LOG_LEVEL: "${LOG_LEVEL:-INFO}"
            OP_CONNECT_HOST: "${OP_CONNECT_HOST:-http://op-connect-api:8080}"
            OP_SERVICE_ACCOUNT_TOKEN: "${OP_SERVICE_ACCOUNT_TOKEN:?}"
            OP_VAULT: "${OP_VAULT:?}"
    op-connect-api:
        environment: *op-session
        #secrets: *1password-credentials-secret
        #volumes: *volumes
    op-connect-sync:
        environment: *op-session
        #secrets: *1password-credentials-secret
        #volumes: *volumes
