[[stack]]
name = "komodo-1p"
tags = ["infrastructure", "1password-connect"]
[stack.config]
server = "localhost"
poll_for_updates = true
auto_update = true
destroy_before_deploy = true
git_account = "b-"
repo = "b-/komodo-op"
branch = "komodo-deploy"
reclone = true
file_paths = [
    "docker-compose.yaml",
    "secrets.compose.yaml",
    "ts.compose.yaml",
    "env.compose.yaml",
    "volumes.compose.yaml",
]
environment = """
KOMODO_API_KEY: [[KOMODO_APIKEY_KEY]]
KOMODO_API_SECRET: [[KOMODO_APIKEY_SECRET]]
KOMODO_HOST: https://komodo.shark-perch.ts.net
LOG_LEVEL: INFO
OP_CONNECT_HOST: http://op-connect-api.shark-perch.ts.net:8080
OP_SERVICE_ACCOUNT_TOKEN: [[OP_SERVICE_ACCOUNT_TOKEN]]
OP_SESSION: [[OP_SESSION]]
#OP_SESSION: /run/secrets/1password-credentials.json
OP_VAULT: [[OP_VAULT]]
SYNC_INTERVAL: 15s
#TS_AUTHKEY_FILE: /run/secrets/ts_authkey_file
TS_AUTHKEY: [[TS_OAUTH_OPCONNECT]]?ephemeral=true
TS_ENABLE_HEALTH_CHECK: true
TS_EXTRA_ARGS: --advertise-tags=tag:op-connect --ssh
#TS_LOCAL_ADDR_PORT: 127.0.0.1:41234
#TS_SERVE_CONFIG: /config/serve.json
TS_STATE: /ts_state
#TS_USERSPACE: false
"""

##

[[resource_sync]]
name = "komodo-1p"
tags = ["infrastructure", "1password-connect", "sync"]
[resource_sync.config]
repo = "b-/komodo-op"
branch = "komodo-deploy"
git_account = "b-"
resource_path = ["stack.toml"]
managed = true
match_tags = ["1password-connect"]
