x-ts-sidecar: &ts-sidecar
  env_file: .env
  volumes:
    - ts_state:/ts_state
  image: tailscale/tailscale:latest
  environment:
    #TS_USERSPACE: false
    # TS_HOSTNAME: set in each container
    TS_ENABLE_HEALTH_CHECK: true
    TS_LOCAL_ADDR_PORT: 127.0.0.1:41234
    TS_STATE: /ts_state
    #TS_SERVE_CONFIG: /config/serve.json
  #    ports: # set per-container
  #      - "8120"
  #    devices:
  #      - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
  #    cap_add:
  #      - net_admin # Tailscale requirement
  #      - sys_module # Tailscale requirement
  healthcheck:
    test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
    interval: 1m # How often to perform the check
    timeout: 10s # Time to wait for the check to succeed
    retries: 3 # Number of retries before marking as unhealthy
    start_period: 10s # Time to wait before starting health checks

services:
  komodo-op:
    depends_on:
      op-connect-api-ts:
        condition: service_started
        required: true

  op-connect-api:
    depends_on:
      op-connect-api-ts:
        condition: service_started
        required: true
    network_mode: service:op-connect-api-ts
    ports: !reset

  op-connect-api-ts:
    <<: *ts-sidecar
    #ports:
    #- "8081:8080"
    environment:
      TS_HOSTNAME: "op-connect-api"

#  op-connect-sync:
#    depends_on:
#      op-connect-sync-ts:
#        condition: service_started
#        required: true
#    ports: !reset
#    network_mode: service:op-connect-sync-ts
#    image: 1password/connect-sync:latest
#  op-connect-sync-ts:
#    <<: *ts-sidecar
#    environment:
#      TS_HOSTNAME: "op-connect-sync"

volumes:
  ts_state:
